{% set name = "fs-gcsfs" %}
{% set version = "0.4.0" %}
{% set sha256 = "ea159de35bfc3a451cf6a1a597a9aab7135d54e8e76ce3b5d3c40f6a2c99f17a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - google-cloud-storage >=1.10.0,<2
    - fs >=2.0.0,<3

test:
  imports:
    - fs_gcsfs

about:
  home: https://github.com/Othoz/gcsfs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python filesystem abstraction of Google Cloud Storage (GCS) implemented as a PyFilesystem2 extension
  doc_url: https://fs-gcsfs.readthedocs.io/
  dev_url: https://github.com/Othoz/gcsfs

extra:
  recipe-maintainers:
    - birnbaum
    - mathiaseitz
    - trendelkampschroer
